apiVersion: v1
kind: Service
metadata:
  name: autoinfra-api
  namespace: autoinfra
spec:
  selector:
    app: autoinfra-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP